version: 0.2

env:
  variables:
    NODE_VERSION: "20"
  parameter-store:
    REACT_APP_API_URL: "/cicd-workshop/react-app-api-url"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Starting Frontend Build..."
      - echo "Build started on `date`"

  pre_build:
    commands:
      - echo "Pre-build phase started"
      - cd frontend
      - echo "Installing dependencies..."
      - npm ci
      
      # Send build start notification
      - |
        if [ ! -z "$SLACK_WEBHOOK_URL" ]; then
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Frontend build started for branch: '${CODEBUILD_SOURCE_VERSION}'"}' \
            $SLACK_WEBHOOK_URL
        fi

  build:
    commands:
      - echo "Build phase started"
      - cd frontend
      - echo "REACT_APP_API_URL=${REACT_APP_API_URL}" > .env
      - npm run build
      - echo "Build completed successfully"

  post_build:
    commands:
      - echo "Deploy phase started"
      - cd frontend
      
      # Deploy to S3
      - echo "Deploying to S3..."
      - aws s3 sync build/ s3://$S3_BUCKET_NAME/ --delete
      
      # Invalidate CloudFront (if configured)
      - |
        if [ ! -z "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
          echo "Invalidating CloudFront..."
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
        fi
      
      # Send success notification
      - |
        if [ ! -z "$SLACK_WEBHOOK_URL" ]; then
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Frontend deployment successful! Branch: '${CODEBUILD_SOURCE_VERSION}' S3 Bucket: '${S3_BUCKET_NAME}'"}' \
            $SLACK_WEBHOOK_URL
        fi

artifacts:
  files:
    - 'frontend/build/**/*'
  name: frontend-build
