name: E2E Tests

on:
  push:
    branches:
      - team3-nischal
    paths:
      - 'e2e-tests/**'
      - '.github/**'

jobs:
  e2e-test:
    runs-on: codebuild-team3-nischal-github-actions-runner-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install E2E dependencies
        working-directory: ./e2e-tests
        run: npm install

      - name: Run Cypress E2E tests
        working-directory: ./e2e-tests
        run: npm run cypress:run
        env:
          CYPRESS_BASE_KEY: ${{ secrets.CYPRESS_API_URL }}
          CYPRESS_API_URL: ${{ secrets.REACT_APP_API_URL }}
